name: Build APK Kivy (Markasir)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode dari repo
        uses: actions/checkout@v4

      - name: Pasang Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instal dependensi dasar
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Instal Android command-line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          mkdir -p latest
          mv cmdline-tools/* latest/ || true

      - name: Terima lisensi SDK & install platform + build-tools
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Siapkan Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Bangun APK
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          buildozer android debug

      - name: Unggah hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Markasir-APK
          path: bin/*.apk
