name: Bangun Markasir APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil kode dari repo
      uses: actions/checkout@v4

    - name: Pasang Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instal dependensi dasar
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip openjdk-17-jdk wget unzip
        pip install --upgrade pip
        pip install buildozer cython

    - name: Persiapkan Buildozer dan SDK Android
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" || true

    - name: Bangun APK
      run: |
        buildozer android debug

    - name: Unggah hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: Markasir-APK
        path: bin/*.apk
